baseURL = "https://francis.run/"
title = "Francis Du"
copyright = "Â© Copyright [Francis Du](https://twitter.com/francis_run) | [Ink](https://github.com/knadh/hugo-ink) theme on [Hugo](https://gohugo.io)"
paginate = 6

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-169239941-1"
disqusShortname = "francis-run"
dataDir = "data"
contentDir = "content"

enableEmoji = true
enableGitInfo = true
enableInlineShortcodes = true
enableRobotsTXT = true
hasCJKLanguage = true

[params]
    subtitle = "Blog"
    description = "Software Enigneer | Co-organizer [@GDG Beijing](https://gdg.community.dev/gdg-beijing) | Technique: Java,Rust,Python,Big Data,etc..."
    avatar = "https://avatars1.githubusercontent.com/u/25944814"
    disableDisqusTypes = ["page"]
    featherIconsCDN = true
    favicon = "img/icon.png"
    images = "img/icon.png"
    title = "Francis Blog"
    mode = "dark"
    busuanzi = true
    social_share = true
    # customCSS = "css/custom.css"  # Custom CSS applied to default styles.
    # customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
    # customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

[author]
name = "Francis Toh"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/blog"
weight = 2

[[menu.main]]
name = "Events"
url = "/events"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "Album"
url = "/album"
weight = 5

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 6

[[menu.main]]
name = "About"
url = "/about"
weight = 7

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/francis-du/"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/francis-du"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/intent/follow?screen_name=francis_run"

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:francis@francisdu.com"

[[params.social]]
name = "Dev.to"
icon = "link-2"
url = "https://dev.to/francisdu"

[[params.social]]
name = "Youtube"
icon = "youtube"
url = "https://www.youtube.com/channel/UCFVmijl279L0A7ub8dzcGkg"

[[params.social]]
name = "Site Status"
icon = "monitor"
url = "https://status.francis.run/"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
tags = "tags"