baseURL = "https://francis.run/"
title = "Francis Du"
pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
googleAnalytics = "UA-169239941-1"
disqusShortname = "francis-run"
dataDir = "data"
contentDir = "content"
enableEmoji = true
enableGitInfo = true
enableInlineShortcodes = true
enableRobotsTXT = true
hasCJKLanguage = true
timeout = 600000
theme = ["hugo-shortcode-gallery"]
copyright = "Â© Copyright [Francis Du](https://twitter.com/francis_run) | [Ink](https://github.com/knadh/hugo-ink) theme on [Hugo](https://gohugo.io)"


# å…è®¸åŸå§‹ HTML
[markup.goldmark.renderer]
unsafe = true

# å¿½ç•¥åŸå§‹ HTML è­¦å‘Š
ignoreLogs = ['warning-goldmark-raw-html']

[params]
    subtitle = "Blog"
    description = "ğŸ’» Data Engineer | ğŸ¦€ Rustacean | ğŸ“· Photographer"
    avatar = "https://avatars1.githubusercontent.com/u/25944814"
    favicon = "img/icon.png"
    title = "Francis Blog"
    mode = "dark"
    busuanzi = true
    social_share = true
    comment = true
    galleryRowHeight = 200
    galleryMargins = 5
    galleryResizeOptions= "800x800 q88 Lanczos"
    galleryPreviewType = "blur"
    galleryThumbnailHoverEffect = "enlarge"
    galleryShowExif="true"
    galleryLoadJQuery="true"
    galleryEmbedPreview="true"


[imaging.exif]
    includeFields = ".*"
    
[pagination]
pagerSize = 10 

[params.author]
name = "Francis Du"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blogs"
url = "/blogs"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "Gallery"
url = "/gallery"
weight = 4

[[menu.main]]
name = "Red Note"
url = "/rednote"
weight = 5

[[menu.main]]
name = "About"
url = "/about"
weight = 6

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/francis-du"

[[params.social]]
name = "Telegram"
icon = "send"
url = "https://t.me/francisdu"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/intent/follow?screen_name=francis_run"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/francis-du/"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
tags = "tags"